---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_image
  pull: if-not-exists
  image: docker:17.09.0-ce
  commands:
  - docker build -t symmetricds .
  environment:
    DOCKER_HOST: tcp://172.17.0.1:2375
  when:
    event:
    - pull_request
    - tag

- name: push_image_to_quay
  pull: if-not-exists
  image: docker:17.09.0-ce
  commands:
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_QUAY_PASSWORD}" "$${DOCKER_REPO}"
  - ./publish.sh "symmetricds" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
  environment:
    DOCKER_BASEDIR: /ukhomeofficedigital/
    DOCKER_HOST: tcp://172.17.0.1:2375
    DOCKER_IMAGE: symmetricds
    DOCKER_QUAY_PASSWORD:
      from_secret: docker_quay_password
    DOCKER_REPO: quay.io
    DOCKER_USERNAME: ukhomeofficedigital+symmetricds
  when:
    event:
    - tag

...
