---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      dry_run: true
      repo: quay.io/ukhomeofficedigital/symmetricds
    when:
      event:
        - pull_request

  - name: docker-build-and-push
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: quay.io/ukhomeofficedigital
      repo: quay.io/ukhomeofficedigital/symmetricds
      tags:
        - "test-upgrade"
      username: ukhomeofficedigital+symmetricds
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_quay_password
    when:
      event:
        - tag

...
