WHENEVER SQLERROR EXIT;

CREATE OR REPLACE FUNCTION SYS.GET_ENV(p_var IN VARCHAR2) RETURN VARCHAR2 IS
   v_return_value VARCHAR2(4000);
BEGIN
   DBMS_SYSTEM.GET_ENV(p_var, v_return_value);
   return v_return_value;
END;
/

COLUMN v NEW_VALUE username
  SELECT COALESCE(SYS.GET_ENV('ORACLE_USER'), 'oracle') AS v
  FROM DUAL;

COLUMN v NEW_VALUE password
  SELECT SYS.GET_ENV('ORACLE_PASSWORD') AS v
  FROM DUAL;

CREATE USER &username IDENTIFIED BY &password PROFILE DEFAULT
  ACCOUNT UNLOCK
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &username;
GRANT CREATE ANY TRIGGER TO &username;
GRANT EXECUTE ON UTL_RAW TO &username;
GRANT RESOURCE TO &username;
