CREATE TABLE "test"
(
  "id" NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
  "name" VARCHAR2(256),
  "date" DATE
);

INSERT INTO "test"
(
  "name",
  "date"
)
VALUES
(
  'foo',
  date '2017-07-24'
);

INSERT INTO "test"
(
  "name",
  "date"
)
VALUES
(
  'bar',
  date '2017-05-31'
);

INSERT INTO "test"
(
  "name",
  "date"
)
VALUES
(
  'baz',
  date '1958-09-29'
);

INSERT INTO "test"
(
  "name",
  "date"
)
VALUES
(
  'quz',
  date '1913-07-06'
);
